name: Linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential clang lld libunwind-dev libfreetype-dev libfontconfig1-dev libharfbuzz-dev libicu-dev libjpeg-dev libpng-dev libwebp-dev qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5opengl5-dev libqt5svg5-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev
    - name: Build
      run: |
        CC=clang CXX=clang++ cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SKIA=ON
        ninja -C build -j2
    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: friction-linux-x86_64
        path: |
          build/src/app/friction
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Development Build (${{ github.sha }})
        tag_name: dev-${{ github.run_number }}
        files: build/src/app/friction
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
